services:
  - type: web
    name: neuroguard-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: PYTHONPATH=. uvicorn app.app:app --host 0.0.0.0 --port 8001
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONPATH
        value: .
      - key: SEGMENTATION_WEIGHTS
        value: unet_trained.pth
